# Generated by Django 5.0.6 on 2026-09-07 09:03

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('class_level', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('AD', 'Admission Test')], max_length=2)),
                ('schedule_note', models.CharField(blank=True, help_text='e.g. Sat/Mon/Wed, 4:00-6:00 PM', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ['class_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_on', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[('rent', 'House rent'), ('teacher', 'Teacher payment'), ('staff', 'Staff salary'), ('electricity', 'Electricity bill'), ('internet', 'Internet bill'), ('printing', 'Photocopy & printing'), ('stationery', 'Stationery'), ('furniture', 'Furniture & equipment'), ('marketing', 'Marketing & publicity'), ('transport', 'Transport'), ('refreshment', 'Refreshment'), ('repair', 'Repair & maintenance'), ('charge', 'Bank / bKash charge'), ('other', 'Other expense')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_to', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank transfer')], default='cash', max_length=10)),
                ('paid_by', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, help_text='Only if the cost belongs to one batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.batch')),
            ],
            options={
                'ordering': ['-spent_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.program'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, help_text='Generated automatically, but you can type your own.', max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('class_level', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('AD', 'Admission Test')], max_length=2)),
                ('school', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('guardian_phone', models.CharField(blank=True, max_length=24)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('joining_date', models.DateField(default=datetime.date.today)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hold', 'On hold'), ('left', 'Left')], default='active', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.batch')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.program')),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, help_text='Which month this fee is FOR (not necessarily when it was paid).', null=True)),
                ('category', models.CharField(choices=[('monthly_fee', 'Monthly fee'), ('admission', 'Admission fee'), ('exam', 'Exam / model test fee'), ('material', 'Sheet / notes'), ('other', 'Other income')], default='monthly_fee', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_on', models.DateField(default=datetime.date.today)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank transfer')], default='cash', max_length=10)),
                ('received_by', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('pay_type', models.CharField(choices=[('fixed', 'Fixed monthly amount'), ('per_student', 'Share of the fees collected'), ('hourly', 'Per class / hourly')], default='fixed', max_length=12)),
                ('fixed_monthly', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Used when pay type is a fixed monthly amount.', max_digits=9)),
                ('share_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Percent of the fee collected on that teacher's courses.", max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='core.subject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('AD', 'Admission Test')], max_length=2)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.teacher')),
            ],
            options={
                'ordering': ['class_level', 'program__name', 'subject__name'],
                'unique_together': {('subject', 'class_level', 'program')},
            },
        ),
        migrations.CreateModel(
            name='TeacherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text="Which month's work this pays for")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_on', models.DateField(default=datetime.date.today)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank transfer')], default='cash', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_payment', to='core.expense')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.teacher')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Always stored as the 1st of the month')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Taka off the monthly fee (waiver, sibling discount).', max_digits=9)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Recalculated from the courses each time you save.', max_digits=9)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.batch')),
                ('courses', models.ManyToManyField(blank=True, related_name='enrollments', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
            ],
            options={
                'ordering': ['-month', 'student__student_id'],
                'unique_together': {('student', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_date', models.DateField(default=datetime.date.today)),
                ('present', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.student')),
            ],
            options={
                'ordering': ['-on_date'],
                'unique_together': {('student', 'batch', 'on_date')},
            },
        ),
    ]
