# Generated by Django 5.0.6 on 2026-09-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='program',
            name='description_bn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon name, e.g. book, mortarboard, rocket-takeoff', max_length=40),
        ),
        migrations.AddField(
            model_name='program',
            name='name_bn',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='program',
            name='show_on_website',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tagline_bn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_bn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation_bn',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='teacher',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.FileField(blank=True, upload_to='teachers/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification_bn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='show_on_website',
            field=models.BooleanField(default=False),
        ),
    ]
