# Generated by Django 5.0.6 on 2026-09-08 08:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_teacher_options_program_description_bn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('routine', 'Class routine'), ('syllabus', 'Syllabus'), ('sheet', 'Lecture sheet'), ('question', 'Question paper'), ('form', 'Form'), ('other', 'Other')], default='other', max_length=12)),
                ('class_level', models.CharField(blank=True, choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('AD', 'Admission Test')], max_length=2)),
                ('file', models.FileField(blank=True, upload_to='downloads/')),
                ('file_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(blank=True, max_length=140)),
                ('title_en', models.CharField(blank=True, max_length=140)),
                ('held_on', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-held_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(blank=True, max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('subtitle_bn', models.CharField(blank=True, max_length=300)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('image', models.FileField(blank=True, upload_to='slides/')),
                ('image_url', models.URLField(blank=True, help_text='Use this instead of uploading when the site runs on Vercel.')),
                ('button_text_bn', models.CharField(blank=True, max_length=60)),
                ('button_text_en', models.CharField(blank=True, max_length=60)),
                ('button_url', models.CharField(blank=True, help_text='A path like /admission/ or a full https:// link.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('body_bn', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='notices/')),
                ('attachment_url', models.URLField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_bn', models.CharField(default='অন্বেষা', max_length=200)),
                ('hero_title_en', models.CharField(default='Onnesha', max_length=200)),
                ('hero_subtitle_bn', models.CharField(blank=True, max_length=300)),
                ('hero_subtitle_en', models.CharField(blank=True, max_length=300)),
                ('hero_image_url', models.URLField(blank=True)),
                ('about_bn', models.TextField(blank=True)),
                ('about_en', models.TextField(blank=True)),
                ('address_bn', models.CharField(blank=True, max_length=200)),
                ('address_en', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('map_embed_url', models.URLField(blank=True, help_text="Google Maps 'Embed a map' src link.")),
                ('established_year', models.CharField(blank=True, max_length=8)),
                ('students_count', models.CharField(blank=True, max_length=12)),
                ('teachers_count', models.CharField(blank=True, max_length=12)),
                ('success_rate', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('class_level', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('AD', 'Admission Test')], max_length=2)),
                ('school', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(max_length=24)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('guardian_phone', models.CharField(blank=True, max_length=24)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('admitted', 'Admitted'), ('closed', 'Not proceeding')], default='new', max_length=12)),
                ('staff_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.program')),
                ('subjects', models.ManyToManyField(blank=True, to='core.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt_bn', models.CharField(blank=True, max_length=300)),
                ('excerpt_en', models.CharField(blank=True, max_length=300)),
                ('body_bn', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True)),
                ('cover', models.FileField(blank=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(blank=True, max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('class_level', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('AD', 'Admission Test')], max_length=2)),
                ('held_on', models.DateField(default=django.utils.timezone.now)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('is_published', models.BooleanField(default=False, help_text='Results are hidden from the site until this is ticked.')),
                ('show_public_list', models.BooleanField(default=True, help_text='Show the merit list to everyone. Untick to allow only private lookup by student ID.')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.program')),
            ],
            options={
                'ordering': ['-held_on'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(blank=True, max_length=20)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('position', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=140)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='website.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.student')),
            ],
            options={
                'ordering': ['position', '-obtained_marks'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_bn', models.CharField(blank=True, max_length=160)),
                ('caption_en', models.CharField(blank=True, max_length=160)),
                ('image', models.FileField(blank=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.galleryalbum')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_bn', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('youtube_url', models.URLField(help_text='Paste the normal YouTube link.')),
                ('class_level', models.CharField(blank=True, choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('AD', 'Admission Test')], max_length=2)),
                ('is_short', models.BooleanField(default=False, help_text='Tick for a short / reel rather than a full lecture.')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('out_of', models.PositiveIntegerField(default=100)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='website.examresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'ordering': ['subject__name'],
                'unique_together': {('result', 'subject')},
            },
        ),
    ]
